services:
  server:
    build: .
    volumes:
      - .:/home/huggingface
      - /usr/share/nginx/html/outputs:/home/huggingface/output
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
